# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
xcode_workspace: Demo/Driftwood_iOS/Driftwood_iOS.xcworkspace
xcode_scheme: Driftwood_iOS
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11
podfile: Demo/Driftwood_iOS/Podfile

